package com.wemanity.scrumbox.android.db.dao.impl;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

import com.wemanity.scrumbox.android.db.dao.DaoSession;
import com.wemanity.scrumbox.android.db.entity.Daily;
import com.wemanity.scrumbox.android.db.entity.DailyOccurrence;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DAILY_OCCURRENCE.
*/
public class DailyOccurrenceDao extends AbstractDao<DailyOccurrence, Long> {


    public static final String TABLENAME = "DAILY_OCCURRENCE";

    /**
     * Properties of entity DailyOccurrence.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Dateexecuted = new Property(1, java.util.Date.class, "dateexecuted", false, "DATEEXECUTED");
        public final static Property Totaltime = new Property(2, Long.class, "totaltime", false, "TOTALTIME");
        public final static Property Dailyid = new Property(3, long.class, "dailyid", false, "DAILYID");
    };

    private DaoSession daoSession;


    public DailyOccurrenceDao(DaoConfig config) {
        super(config);
    }

    public DailyOccurrenceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DAILY_OCCURRENCE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DATEEXECUTED' INTEGER," + // 1: dateexecuted
                "'TOTALTIME' INTEGER," + // 2: totaltime
                "'DAILYID' INTEGER NOT NULL );"); // 3: dailyid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DAILY_OCCURRENCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DailyOccurrence entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        java.util.Date dateexecuted = entity.getDateexecuted();
        if (dateexecuted != null) {
            stmt.bindLong(2, dateexecuted.getTime());
        }

        Long totaltime = entity.getTotaltime();
        if (totaltime != null) {
            stmt.bindLong(3, totaltime);
        }
        stmt.bindLong(4, entity.getDailyid());
    }

    @Override
    protected void attachEntity(DailyOccurrence entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public DailyOccurrence readEntity(Cursor cursor, int offset) {
        DailyOccurrence entity = new DailyOccurrence( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // dateexecuted
                cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // totaltime
                cursor.getLong(offset + 3) // dailyid
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DailyOccurrence entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDateexecuted(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setTotaltime(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setDailyid(cursor.getLong(offset + 3));
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DailyOccurrence entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(DailyOccurrence entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDailyDao().getAllColumns());
            builder.append(" FROM DAILY_OCCURRENCE T");
            builder.append(" LEFT JOIN DAILY T0 ON T.'DAILYID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected DailyOccurrence loadCurrentDeep(Cursor cursor, boolean lock) {
        DailyOccurrence entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Daily daily = loadCurrentOther(daoSession.getDailyDao(), cursor, offset);
        if(daily != null) {
            entity.setDaily(daily);
        }

        return entity;
    }

    public DailyOccurrence loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DailyOccurrence> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DailyOccurrence> list = new ArrayList<DailyOccurrence>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<DailyOccurrence> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }


    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DailyOccurrence> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
}
