package com.wemanity.scrumbox.android.db.dao.impl;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.wemanity.scrumbox.android.db.dao.DaoSession;
import com.wemanity.scrumbox.android.db.dao.ParticipantDao;
import com.wemanity.scrumbox.android.db.entity.Daily;
import com.wemanity.scrumbox.android.db.entity.Member;
import com.wemanity.scrumbox.android.db.entity.Participant;
import com.wemanity.scrumbox.android.db.entity.Role;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PARTICIPANT.
*/
public class ParticipantGreenDao extends AbstractDao<Participant, Long> implements ParticipantDao {

    public static final String TABLENAME = "PARTICIPANT";

    /**
     * Properties of entity Participant.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Memberid = new Property(1, long.class, "memberid", false, "MEMBERID");
        public final static Property Roleid = new Property(2, long.class, "roleid", false, "ROLEID");
        public final static Property Dailyid = new Property(3, long.class, "dailyid", false, "DAILYID");
        public final static Property Excludemonday = new Property(4, Boolean.class, "excludemonday", false, "EXCLUDEMONDAY");
        public final static Property Excludethuesday = new Property(5, Boolean.class, "excludethuesday", false, "EXCLUDETHUESDAY");
        public final static Property Excludewednesday = new Property(6, Boolean.class, "excludewednesday", false, "EXCLUDEWEDNESDAY");
        public final static Property Excludethursday = new Property(7, Boolean.class, "excludethursday", false, "EXCLUDETHURSDAY");
        public final static Property Excludefriday = new Property(8, Boolean.class, "excludefriday", false, "EXCLUDEFRIDAY");
        public final static Property Excludesaturday = new Property(9, Boolean.class, "excludesaturday", false, "EXCLUDESATURDAY");
        public final static Property Excludesunday = new Property(10, Boolean.class, "excludesunday", false, "EXCLUDESUNDAY");
        public final static Property Participantid = new Property(11, long.class, "participantid", false, "PARTICIPANTID");
    };

    private DaoSession daoSession;

    private Query<Participant> daily_ParticipantsQuery;
    private Query<Participant> participation_ParticipantListQuery;

    public ParticipantGreenDao(DaoConfig config) {
        super(config);
    }
    
    public ParticipantGreenDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PARTICIPANT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MEMBERID' INTEGER NOT NULL ," + // 1: memberid
                "'ROLEID' INTEGER NOT NULL ," + // 2: roleid
                "'DAILYID' INTEGER NOT NULL ," + // 3: dailyid
                "'EXCLUDEMONDAY' INTEGER," + // 4: excludemonday
                "'EXCLUDETHUESDAY' INTEGER," + // 5: excludethuesday
                "'EXCLUDEWEDNESDAY' INTEGER," + // 6: excludewednesday
                "'EXCLUDETHURSDAY' INTEGER," + // 7: excludethursday
                "'EXCLUDEFRIDAY' INTEGER," + // 8: excludefriday
                "'EXCLUDESATURDAY' INTEGER," + // 9: excludesaturday
                "'EXCLUDESUNDAY' INTEGER," + // 10: excludesunday
                "'PARTICIPANTID' INTEGER NOT NULL );"); // 11: participantid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PARTICIPANT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Participant entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMemberid());
        stmt.bindLong(3, entity.getRoleid());
        stmt.bindLong(4, entity.getDailyid());
 
        Boolean excludemonday = entity.getExcludemonday();
        if (excludemonday != null) {
            stmt.bindLong(5, excludemonday ? 1l: 0l);
        }
 
        Boolean excludethuesday = entity.getExcludethuesday();
        if (excludethuesday != null) {
            stmt.bindLong(6, excludethuesday ? 1l: 0l);
        }
 
        Boolean excludewednesday = entity.getExcludewednesday();
        if (excludewednesday != null) {
            stmt.bindLong(7, excludewednesday ? 1l: 0l);
        }
 
        Boolean excludethursday = entity.getExcludethursday();
        if (excludethursday != null) {
            stmt.bindLong(8, excludethursday ? 1l: 0l);
        }
 
        Boolean excludefriday = entity.getExcludefriday();
        if (excludefriday != null) {
            stmt.bindLong(9, excludefriday ? 1l: 0l);
        }
 
        Boolean excludesaturday = entity.getExcludesaturday();
        if (excludesaturday != null) {
            stmt.bindLong(10, excludesaturday ? 1l: 0l);
        }
 
        Boolean excludesunday = entity.getExcludesunday();
        if (excludesunday != null) {
            stmt.bindLong(11, excludesunday ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(Participant entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Participant readEntity(Cursor cursor, int offset) {
        Participant entity = new Participant( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // memberid
            cursor.getLong(offset + 2), // roleid
            cursor.getLong(offset + 3), // dailyid
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // excludemonday
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // excludethuesday
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // excludewednesday
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // excludethursday
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // excludefriday
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // excludesaturday
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0 // excludesunday
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Participant entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMemberid(cursor.getLong(offset + 1));
        entity.setRoleid(cursor.getLong(offset + 2));
        entity.setDailyid(cursor.getLong(offset + 3));
        entity.setExcludemonday(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setExcludethuesday(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setExcludewednesday(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setExcludethursday(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setExcludefriday(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setExcludesaturday(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setExcludesunday(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Participant entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Participant entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "participants" to-many relationship of Daily. */
    public List<Participant> _queryDaily_Participants(long dailyid) {
        synchronized (this) {
            if (daily_ParticipantsQuery == null) {
                QueryBuilder<Participant> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Dailyid.eq(null));
                queryBuilder.orderRaw("ROLEID ASC,MEMBERID ASC");
                daily_ParticipantsQuery = queryBuilder.build();
            }
        }
        Query<Participant> query = daily_ParticipantsQuery.forCurrentThread();
        query.setParameter(0, dailyid);
        return query.list();
    }

    /** Internal query to resolve the "participantList" to-many relationship of Participation. */
    public List<Participant> _queryParticipation_ParticipantList(long participantid) {
        synchronized (this) {
            if (participation_ParticipantListQuery == null) {
                QueryBuilder<Participant> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Participantid.eq(null));
                participation_ParticipantListQuery = queryBuilder.build();
            }
        }
        Query<Participant> query = participation_ParticipantListQuery.forCurrentThread();
        query.setParameter(0, participantid);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMemberDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getRoleDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getDailyDao().getAllColumns());
            builder.append(" FROM PARTICIPANT T");
            builder.append(" LEFT JOIN MEMBER T0 ON T.'MEMBERID'=T0.'_id'");
            builder.append(" LEFT JOIN ROLE T1 ON T.'ROLEID'=T1.'_id'");
            builder.append(" LEFT JOIN DAILY T2 ON T.'DAILYID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Participant loadCurrentDeep(Cursor cursor, boolean lock) {
        Participant entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Member member = loadCurrentOther(daoSession.getMemberDao(), cursor, offset);
         if(member != null) {
            entity.setMember(member);
        }
        offset += daoSession.getMemberDao().getAllColumns().length;

        Role role = loadCurrentOther(daoSession.getRoleDao(), cursor, offset);
         if(role != null) {
            entity.setRole(role);
        }
        offset += daoSession.getRoleDao().getAllColumns().length;

        Daily daily = loadCurrentOther(daoSession.getDailyDao(), cursor, offset);
         if(daily != null) {
            entity.setDaily(daily);
        }

        return entity;    
    }

    public Participant loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Participant> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Participant> list = new ArrayList<Participant>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Participant> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Participant> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
