package com.wemanity.scrumbox.android.db.entity;

import com.wemanity.scrumbox.android.db.dao.DaoSession;
import com.wemanity.scrumbox.android.db.dao.impl.DailyDao;
import com.wemanity.scrumbox.android.db.dao.impl.DailyOccurrenceDao;
import com.wemanity.scrumbox.android.db.dao.impl.ParticipationDao;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DAILY_OCCURRENCE.
 */
public class DailyOccurrence implements Entity {
    private Long id;
    private java.util.Date dateexecuted;
    private Long totaltime;
    private long dailyid;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DailyOccurrenceDao myDao;

    private Daily daily;
    private Long daily__resolvedKey;

    private List<Participation> participations;

    public DailyOccurrence() {
    }

    public DailyOccurrence(Long id) {
        this.id = id;
    }

    public DailyOccurrence(Long id, java.util.Date dateexecuted, Long totaltime, long dailyid) {
        this.id = id;
        this.dateexecuted = dateexecuted;
        this.totaltime = totaltime;
        this.dailyid = dailyid;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDailyOccurrenceDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDateexecuted() {
        return dateexecuted;
    }

    public void setDateexecuted(java.util.Date dateexecuted) {
        this.dateexecuted = dateexecuted;
    }

    public Long getTotaltime() {
        return totaltime;
    }

    public void setTotaltime(Long totaltime) {
        this.totaltime = totaltime;
    }

    public long getDailyid() {
        return dailyid;
    }

    public void setDailyid(long dailyid) {
        this.dailyid = dailyid;
    }

    /** To-one relationship, resolved on first access. */
    public Daily getDaily() {
        long __key = this.dailyid;
        if (daily__resolvedKey == null || !daily__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DailyDao targetDao = daoSession.getDailyDao();
            Daily dailyNew = targetDao.load(__key);
            synchronized (this) {
                daily = dailyNew;
                daily__resolvedKey = __key;
            }
        }
        return daily;
    }

    public void setDaily(Daily daily) {
        if (daily == null) {
            throw new DaoException("To-one property 'dailyid' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.daily = daily;
            dailyid = daily.getId();
            daily__resolvedKey = dailyid;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Participation> getParticipations() {
        if (participations == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ParticipationDao targetDao = daoSession.getParticipationDao();
            List<Participation> participationsNew = targetDao._queryDailyOccurrence_Participations(id);
            synchronized (this) {
                if(participations == null) {
                    participations = participationsNew;
                }
            }
        }
        return participations;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetParticipations() {
        participations = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

}
