package com.wemanity.scrumbox.android.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.Arrays;

/**
 * Entity mapped to table MEMBER.
 */
public class Member implements Entity {

    private Long id;
    private String nickname;
    private byte[] image;

    public Member() {
    }

    public Member(Long id) {
        this.id = id;
    }

    public Member(Long id, String nickname, byte[] image) {
        this.id = id;
        this.nickname = nickname;
        this.image = image;
    }

    @Override
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Member member = (Member) o;

        if (!id.equals(member.id)) return false;
        if (!Arrays.equals(image, member.image)) return false;
        if (!nickname.equals(member.nickname)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = nickname.hashCode();
        result = 31 * result + (image != null ? Arrays.hashCode(image) : 0);
        return result;
    }
}
