package com.wemanity.scrumbox.android.db.entity;

import java.util.List;
import com.wemanity.scrumbox.android.db.dao.DaoSession;
import com.wemanity.scrumbox.android.db.dao.impl.ParticipantGreenDao;
import com.wemanity.scrumbox.android.db.dao.impl.ParticipationGreenDao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PARTICIPATION.
 */
public class Participation {

    private Long id;
    private Integer personaltime;
    private long participantid;
    private long dailyoccurrenceid;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ParticipationGreenDao myDao;

    private List<Participant> participantList;

    public Participation() {
    }

    public Participation(Long id) {
        this.id = id;
    }

    public Participation(Long id, Integer personaltime, long participantid, long dailyoccurrenceid) {
        this.id = id;
        this.personaltime = personaltime;
        this.participantid = participantid;
        this.dailyoccurrenceid = dailyoccurrenceid;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getParticipationDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPersonaltime() {
        return personaltime;
    }

    public void setPersonaltime(Integer personaltime) {
        this.personaltime = personaltime;
    }

    public long getParticipantid() {
        return participantid;
    }

    public void setParticipantid(long participantid) {
        this.participantid = participantid;
    }

    public long getDailyoccurrenceid() {
        return dailyoccurrenceid;
    }

    public void setDailyoccurrenceid(long dailyoccurrenceid) {
        this.dailyoccurrenceid = dailyoccurrenceid;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Participant> getParticipantList() {
        if (participantList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ParticipantGreenDao targetDao = daoSession.getParticipantDao();
            List<Participant> participantListNew = targetDao._queryParticipation_ParticipantList(id);
            synchronized (this) {
                if(participantList == null) {
                    participantList = participantListNew;
                }
            }
        }
        return participantList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetParticipantList() {
        participantList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
